#!/bin/bash

f=3 b=4
for j in f b; do
for i in {0..7}; do
printf -v $j$i %b "\e[${!j}${i}m"
done
done
bld=$'\e[1m'
rst=$'\e[0m'
inv=$'\e[7m'
cat << EOF
$bld$f1▀■▄$rst$f1▀■▄$bld$f3▀■▄$rst$f3▀■▄$bld$f2▀■▄$rst$f2▀■▄$bld$f6▀■▄$rst$f6▀■▄$bld$f4▀■▄$rst$f4▀■▄$bld$f5▀■▄$rst$f5▀■▄$bld$f7▀■▄$rst$f7▀■▄
$bld$f1▄■▀$rst$f1▄■▀$bld$f3▄■▀$rst$f3▄■▀$bld$f2▄■▀$rst$f2▄■▀$bld$f6▄■▀$rst$f6▄■▀$bld$f4▄■▀$rst$f4▄■▀$bld$f5▄■▀$rst$f5▄■▀$bld$f7▄■▀$rst$f7▄■▀
EOF