#!/usr/bin/env bash
echo -e '
 \e[31m▒▒▒▒\e[0m \e[1m\e[31m▒▒\e[0m   \e[32m▒▒▒▒\e[0m \e[1m\e[32m▒▒\e[0m   \e[33m▒▒▒▒\e[0m \e[1m\e[33m▒▒\e[0m   \e[34m▒▒▒▒\e[0m \e[1m\e[34m▒▒\e[0m   \e[35m▒▒▒▒\e[0m \e[1m\e[35m▒▒\e[0m   \e[36m▒▒▒▒\e[0m \e[1m\e[36m▒▒\e[0m
 \e[31m▒▒ ■\e[0m \e[1m\e[31m▒▒\e[0m   \e[32m▒▒ ■\e[0m \e[1m\e[32m▒▒\e[0m   \e[33m▒▒ ■\e[0m \e[1m\e[33m▒▒\e[0m   \e[34m▒▒ ■\e[0m \e[1m\e[34m▒▒\e[0m   \e[35m▒▒ ■\e[0m \e[1m\e[35m▒▒\e[0m   \e[36m▒▒ ■\e[0m \e[1m\e[36m▒▒\e[0m
 \e[31m▒▒ \e[0m\e[1m\e[31m▒▒▒▒\e[0m   \e[32m▒▒ \e[0m\e[1m\e[32m▒▒▒▒\e[0m   \e[33m▒▒ \e[0m\e[1m\e[33m▒▒▒▒\e[0m   \e[34m▒▒ \e[0m\e[1m\e[34m▒▒▒▒\e[0m   \e[35m▒▒ \e[0m\e[1m\e[35m▒▒▒▒\e[0m   \e[36m▒▒ \e[0m\e[1m\e[36m▒▒▒▒\e[0m
'